version: 3.1

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/etc/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    

networks:
  mongoCluster:
  
# docker run --name some-mongo -v /my/custom:/etc/mongo -d mongo --config /etc/mongo/mongod.conf